#!/bin/sh
set -e
if [ "$1" = "configure" ]; then
	ln -sf /usr/share/yubi-tcl/tools/yubi_key_mgmt.tcl /usr/bin/yubi_key_mgmt
	ln -sf /usr/share/yubi-tcl/tools/yubi_otpinfo.tcl /usr/bin/yubi_otpinfo
	chmod 2750 /etc/data/keys /etc/data/users
	chgrp -R www-data /etc/data/keys /etc/data/users
fi

